name: Automated Database Backup

on:
  schedule:
    - cron: "0 0 * * *"   # Runs daily at midnight UTC
  workflow_dispatch:       # Also allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      OCI_S3_ACCESS_KEY: ${{ secrets.OCI_S3_ACCESS_KEY }}
      OCI_S3_SECRET_KEY: ${{ secrets.OCI_S3_SECRET_KEY }}
      OCI_S3_BUCKET: ${{ secrets.OCI_S3_BUCKET }}
      OCI_S3_ENDPOINT: ${{ secrets.OCI_S3_ENDPOINT }}
      OCI_S3_REGION: ${{ secrets.OCI_S3_REGION }}
      DO_HOST: ${{ secrets.DO_HOST }}
      DO_USER: ${{ secrets.DO_USER }}
      DO_SSH_PORT: ${{ secrets.DO_SSH_PORT }}
      DO_SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openssh-client awscli

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$DO_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $DO_SSH_PORT $DO_HOST >> ~/.ssh/known_hosts

      - name: Dump database and upload to OCI
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          BACKUP_FILE="backup_${TIMESTAMP}.sql.gz"

          echo "Creating MySQL backup on remote server..."
          ssh -p $DO_SSH_PORT $DO_USER@$DO_HOST "mysqldump --all-databases | gzip > /tmp/${BACKUP_FILE}"

          echo "Downloading backup from remote server..."
          scp -P $DO_SSH_PORT $DO_USER@$DO_HOST:/tmp/${BACKUP_FILE} .

          echo "Uploading to OCI Object Storage..."
          AWS_ACCESS_KEY_ID=$OCI_S3_ACCESS_KEY \
          AWS_SECRET_ACCESS_KEY=$OCI_S3_SECRET_KEY \
          aws s3 cp $BACKUP_FILE s3://$OCI_S3_BUCKET/ \
            --endpoint-url $OCI_S3_ENDPOINT \
            --region $OCI_S3_REGION

          echo "Cleaning up..."
          ssh -p $DO_SSH_PORT $DO_USER@$DO_HOST "rm /tmp/${BACKUP_FILE}"
          rm $BACKUP_FILE

      - name: Done
        run: echo "✅ Backup completed and uploaded to OCI successfully!"
